import type { QSO } from '../../types/qso'
import type { ExportStrategy, ExportOptions } from '../../types/export'
import { formatDateForAdif, formatTimeForAdif } from '../../utils/dateTime'

function adifField(name: string, value: string): string {
  return `<${name}:${value.length}>${value}`
}

export const adifStrategy: ExportStrategy = {
  mimeType: 'application/adif',
  fileExtension: 'adi',

  export(qsos: QSO[], _options: ExportOptions): string {
    const header = [
      'Generated by QSOlog',
      adifField('ADIF_VER', '3.1.4'),
      adifField('PROGRAMID', 'QSOlog'),
      adifField('PROGRAMVERSION', '0.1.0'),
      '<EOH>',
      '',
    ].join('\n')

    const records = qsos.map((qso) => {
      const fields: string[] = []

      fields.push(adifField('QSO_DATE', formatDateForAdif(qso.date)))
      fields.push(adifField('TIME_ON', formatTimeForAdif(qso.date)))
      fields.push(adifField('CALL', qso.callsign))
      if (qso.name) fields.push(adifField('NAME', qso.name))
      if (qso.country) fields.push(adifField('COUNTRY', qso.country))
      fields.push(adifField('MODE', qso.mode))
      if (qso.band) fields.push(adifField('BAND', qso.band))
      if (qso.frequency) fields.push(adifField('FREQ', qso.frequency))
      if (qso.power) fields.push(adifField('TX_PWR', qso.power))
      fields.push(adifField('RST_SENT', qso.rstSent))
      fields.push(adifField('RST_RCVD', qso.rstReceived))
      if (qso.locator) fields.push(adifField('GRIDSQUARE', qso.locator))
      if (qso.myLocator) fields.push(adifField('MY_GRIDSQUARE', qso.myLocator))
      if (qso.remarks) fields.push(adifField('COMMENT', qso.remarks))

      const qslSentMap: Record<string, string> = { yes: 'Y', no: 'N', requested: 'R' }
      const qslRcvdMap: Record<string, string> = { yes: 'Y', no: 'N', requested: 'R' }
      fields.push(adifField('QSL_SENT', qslSentMap[qso.qslSent] ?? 'N'))
      fields.push(adifField('QSL_RCVD', qslRcvdMap[qso.qslReceived] ?? 'N'))

      fields.push('<EOR>')
      return fields.join(' ')
    })

    return header + records.join('\n') + '\n'
  },
}
