import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { QSO } from '../../types/qso'
import { formatUtcDateTime } from '../../utils/dateTime'

export interface PdfReportOptions {
  stationCallsign: string
  dateFrom?: string
  dateTo?: string
}

export function generatePdfReport(qsos: QSO[], options: PdfReportOptions): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })

  // Header
  doc.setFontSize(16)
  doc.text('funk-log', 14, 15)

  doc.setFontSize(10)
  if (options.stationCallsign) {
    doc.text(`Station: ${options.stationCallsign}`, 14, 22)
  }

  let dateRange = ''
  if (options.dateFrom || options.dateTo) {
    dateRange = `${options.dateFrom ?? '...'} - ${options.dateTo ?? '...'}`
  }
  if (dateRange) {
    doc.text(dateRange, 14, 28)
  }

  // Table
  const headers = [['#', 'Date/Time', 'Callsign', 'Mode', 'Freq', 'Band', 'RST S', 'RST R', 'QSL S', 'QSL R', 'Remarks']]

  const body = qsos.map((qso) => [
    String(qso.sequenceNumber),
    formatUtcDateTime(qso.date),
    qso.callsign,
    qso.mode,
    qso.frequency,
    qso.band,
    qso.rstSent,
    qso.rstReceived,
    qso.qslSent === 'yes' ? 'Y' : qso.qslSent === 'requested' ? 'R' : 'N',
    qso.qslReceived === 'yes' ? 'Y' : qso.qslReceived === 'requested' ? 'R' : 'N',
    qso.remarks.slice(0, 40),
  ])

  autoTable(doc, {
    head: headers,
    body,
    startY: dateRange ? 33 : options.stationCallsign ? 27 : 20,
    styles: { fontSize: 7, cellPadding: 1.5 },
    headStyles: { fillColor: [30, 41, 59] },
  })

  // Footer summary
  const uniqueBands = [...new Set(qsos.map((q) => q.band).filter(Boolean))]
  const uniqueModes = [...new Set(qsos.map((q) => q.mode).filter(Boolean))]
  const summary = `Total: ${qsos.length} QSOs | Bands: ${uniqueBands.join(', ')} | Modes: ${uniqueModes.join(', ')}`

  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(8)
  doc.text(summary, 14, pageHeight - 10)
  doc.text(`Generated by funk-log | ${new Date().toISOString().slice(0, 10)}`, 14, pageHeight - 6)

  doc.save('funk-log-report.pdf')
}
