import { describe, it, expect } from 'vitest'
import { adifImporter } from '../../../../src/services/import/adifImporter'

const sampleAdif = `Generated by test
<ADIF_VER:5>3.1.4
<EOH>
<QSO_DATE:8>20240315 <TIME_ON:4>1430 <CALL:6>DL1ABC <MODE:3>SSB <BAND:3>20m <FREQ:6>14.200 <RST_SENT:2>59 <RST_RCVD:2>57 <QSL_SENT:1>Y <QSL_RCVD:1>N <COMMENT:7>Contest <EOR>
<QSO_DATE:8>20240316 <TIME_ON:4>0800 <CALL:5>G3XYZ <MODE:2>CW <BAND:3>40m <RST_SENT:3>599 <RST_RCVD:3>579 <QSL_SENT:1>N <QSL_RCVD:1>R <EOR>
`

describe('adifImporter.parse', () => {
  it('parses ADIF records', () => {
    const result = adifImporter.parse(sampleAdif)
    expect(result).toHaveLength(2)
  })

  it('maps callsign and mode', () => {
    const result = adifImporter.parse(sampleAdif)
    expect(result[0].callsign).toBe('DL1ABC')
    expect(result[0].mode).toBe('SSB')
  })

  it('converts ADIF date to ISO format', () => {
    const result = adifImporter.parse(sampleAdif)
    expect(result[0].date).toBe('2024-03-15T14:30:00.000Z')
  })

  it('maps QSL status', () => {
    const result = adifImporter.parse(sampleAdif)
    expect(result[0].qslSent).toBe('yes')
    expect(result[0].qslReceived).toBe('no')
    expect(result[1].qslSent).toBe('no')
    expect(result[1].qslReceived).toBe('requested')
  })

  it('includes band and frequency', () => {
    const result = adifImporter.parse(sampleAdif)
    expect(result[0].band).toBe('20m')
    expect(result[0].frequency).toBe('14.200')
  })

  it('includes remarks from COMMENT field', () => {
    const result = adifImporter.parse(sampleAdif)
    expect(result[0].remarks).toBe('Contest')
  })
})

describe('adifImporter.validate', () => {
  it('passes for valid records', () => {
    const result = adifImporter.validate([
      { callsign: 'DL1ABC', date: '2024-03-15T14:30:00.000Z' },
    ])
    expect(result.valid).toBe(true)
  })

  it('fails for missing required fields', () => {
    const result = adifImporter.validate([
      { callsign: '', date: '' },
    ])
    expect(result.valid).toBe(false)
    expect(result.errors).toHaveLength(2)
  })
})
